title: Paradise Safaris Africa
description: This is the place to be, to read curated posts by DoDo Mukunzi. I write about different cutting edge technologies like Angular2, Express, Node.JS, MongoDB, Ruby on Rails, Postgresql, HTML5, CSS3, Bootstrap, SASS, Pug Jade, and all the good stuff.

url: paradisesafarisafrica.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Safaris Destinations
   url: /destinations
 - title: Gorrila Safaris
   url: /gorilla
 - title: Hiking Safaris
   url: /hiking
 - title: Car Rentals
   url: /rentals
 - title: About
   url: /about
 - title: News
   url: /articles

social:
   youtube: paradisesafarisafrica
   twitter: paradisesafaris
   email: info@paradisesafarisafrica.com

# google_analytics: "UA-58263416-1"
